server:
  port: 8080

spring:
  application:
    name: snore
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

# TODO: MariaDB dialect 설정